### ISSUE TITLE
Ask NASA folks about RocketChat on iPhone

### ISSUE THREAD

**Issue by sewardlee337** [lj42/sonification#4]
So that notifications are easier to track.

**Comment by lj42** [comment]
sent email just now - awaiting reply

**Comment by lj42** [comment]
Haven't heard back yet - might ping tomorrow

**Comment by lj42** [comment]
Claire responded saying no-one at NASA knows anything about RocketChat...

**Comment by sewardlee337** [comment]
Not sure if following is helpful, but worth a shot at linking...
https://github.com/RocketChat/Rocket.Chat.iOS

**Comment by sewardlee337** [comment]
Looks like you have to be mentioned in a chat message (e.g. `@sewardlee337`) in order to get an email notification. Otherwise, you just have to periodically check RocketChat.

Closing for now. Perhaps will revisit in the future.

**Comment by lj42** [comment]
On further enquiries, No one knows who owns rocket chat to give us the permissions required to use the app, so I think mentioning by handle in chat message has been working fine. Double closed!
