### ISSUE TITLE
Prepare and share sound files for first sonification attempt

### ISSUE THREAD

**Issue by sewardlee337** [lj42/sonification#6]
Find a convenient place to store and share sound files that we will be needing for this project.

**Comment by lj42** [comment]
Sounds ready to share (MP3 files)
what's the best way to share? wetransfer  or link or google drive ? could also do dropbox...

**Comment by sewardlee337** [comment]
Currently working with the `.wav` files. At some point file size may be an issue, but we'll cross that bridge when we get there...

**Comment by lj42** [comment]
can encode the `.wav` files at a much lower resolution, say a quarter of the current sizes...

**Comment by sewardlee337** [comment]
Let's close for now. We can revisit when this issue comes up again.
